#ifndef AUTHENTICATIONSERVICE_GLOBAL_H
#define AUTHENTICATIONSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUTHENTICATIONSERVICE_LIBRARY)
#  define AUTHENTICATIONSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUTHENTICATIONSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTHENTICATIONSERVICE_GLOBAL_H
