#ifndef DATABASESERVICE_GLOBAL_H
#define DATABASESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASESERVICE_LIBRARY)
#  define DATABASESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATABASESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASESERVICE_GLOBAL_H
